export const NORMAL_INBOX_TEST_FIXTURES = [
  { key: "wellness-intro", brand: "Northstar Wellness", subject: "Spring wellness story", category: "action_needed", summary: "A wellness brand introduced a possible project and asked what partnerships are a fit.", body: "We're planning a spring wellness story and think your content style could fit. Could you tell us more about the kinds of partnerships you enjoy?" },
  { key: "skincare-kit", brand: "Harbor Skin", subject: "Creator profile request", category: "action_needed", summary: "A skincare team asked for a current media kit and audience overview.", body: "Could you send your current media kit and audience overview? We're exploring creators for an upcoming skincare feature." },
  { key: "preview-invite", brand: "Juniper Labs", subject: "Virtual product preview", category: "action_needed", summary: "A brand invited the creator to learn more at a virtual product preview.", body: "We'd love to invite you to a virtual product preview next month. Would you like the event details?" },
  { key: "desk-accessories", brand: "Arc Desk", subject: "Desk setup collaboration inquiry", category: "action_needed", summary: "An accessories brand noticed a recent desk setup video and asked about interest.", body: "Your recent desk setup video caught our eye. Are you interested in learning about a possible accessories campaign?" },
  { key: "creator-spotlight", brand: "Canvas Journal", subject: "Creator spotlight profile", category: "action_needed", summary: "A publication requested a short creator bio and preferred social links.", body: "We are putting together a creator spotlight and would like a short bio and your preferred social links." },
  { key: "sample-interest", brand: "ClearSpring", subject: "New hydration bottle sample", category: "action_needed", summary: "A product team asked whether the creator wants to receive a sample for consideration.", body: "Would you be open to receiving a sample of our new hydration bottle for consideration?" },
  { key: "content-focus", brand: "Brightside Creative", subject: "Your current content focus", category: "action_needed", summary: "A creative team asked which content categories are currently most relevant.", body: "Could you tell us which content categories you are focusing on this season?" },
  { key: "travel-brief", brand: "Atlas Weekend", subject: "Destination story introduction", category: "action_needed", summary: "A travel brand wants to share a destination brief for initial review.", body: "We enjoyed your recent travel post and would like to share a destination brief for you to review." },
  { key: "profile-review", brand: "Mosaic Goods", subject: "Creator profile received", category: "fyi", summary: "A brand confirmed that the creator profile is under review; no reply is needed.", body: "Thanks for sending your profile. Our team is reviewing it and will follow up with next steps." },
  { key: "newsletter-confirmed", brand: "Creator Field Notes", subject: "Creator newsletter confirmed", category: "fyi", summary: "A creator newsletter registration was confirmed; no reply is needed.", body: "Your registration for our creator newsletter is confirmed. We'll send the next edition when it is ready." },
] as const;

export const NORMAL_INBOX_TEST_REPLY = "Thanks for reaching out. Could you share more context about the project goals, expected scope, timeline, and the audience you hope to reach?\n\nBest,\nYafet";
